import Head from 'next/head'
import { Inter } from 'next/font/google'
import Footer from "@/Components/Layouts/Footer";
import Header from "@/Components/Layouts/Header";
import Empower from "@/Components/Main/Empower";
import Impact from "@/Components/Main/Impact";
import Partners from "@/Components/Main/Partners";
import Swipes from "@/Components/Utils/Slider";
import React from "react";
import Care from "@/Components/Main/Care";
import {Box} from "@mui/system";
import Life from "@/Components/Main/Life";
import Hero from '@/Components/Main/Hero';
import Paper from '@mui/material/Paper';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <Paper elevation={0}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header/>
        <Hero/>
        <Life/>
      <Empower/>
      <Care/>
        <Impact/>
        <Partners/>
        <Footer/>
    </Paper>
  )
}
